[project]
name = "eo-ml-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow[celery]>=3.3.1",
    "geopandas>=1.1.4",
    "odc-stac>=0.5.3",
    "planetary-computer>=1.0.0",
    "pystac-client>=0.9.0",
    "pytest>=9.1.1",
    "rioxarray>=0.23.0",
    "tqdm>=4.70.0",
    "utm>=0.9.0",
    "zarr>=3.3.0",
]

[dependency-groups]
dev = [
    "pytest-cov>=7.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/eo_ml_pipeline"]
